Add kdesrc

diff --git a/bash/dot-bashrc b/bash/dot-bashrc
--- a/bash/dot-bashrc
+++ b/bash/dot-bashrc
@@ -70,3 +70,40 @@ export PROMPT_COMMAND='echo -ne "\033]2;${PWD/#${HOME}/\~}\007"'
 if [ -f $HOME/.local/prog/vcpkg/scripts/vcpkg_completion.bash ]; then
     source $HOME/.local/prog/vcpkg/scripts/vcpkg_completion.bash
 fi
+
+# kdesrc-build #################################################################
+
+## Add kdesrc-build to PATH
+export PATH="$HOME/Projects/Contribute/kdesrc-build/:$PATH"
+
+## Autocomplete for kdesrc-run
+function _comp-kdesrc-run
+{
+  local cur
+  COMPREPLY=()
+  cur="${COMP_WORDS[COMP_CWORD]}"
+
+  # Complete only the first argument
+  if [[ $COMP_CWORD != 1 ]]; then
+    return 0
+  fi
+
+  # Retrieve build modules through kdesrc-run
+  # If the exit status indicates failure, set the wordlist empty to avoid
+  # unrelated messages.
+  local modules
+  if ! modules=$(kdesrc-run --list-installed);
+  then
+      modules=""
+  fi
+
+  # Return completions that match the current word
+  COMPREPLY=( $(compgen -W "${modules}" -- "$cur") )
+
+  return 0
+}
+
+## Register autocomplete function
+complete -o nospace -F _comp-kdesrc-run kdesrc-run
+
+################################################################################
